/****** Object:  Table [dbo].[com_log_comprobante_xml]    Script Date: 4/27/2026 9:42:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[com_log_comprobante_xml](
	[co_id_comprobante] [decimal](18, 0) NOT NULL,
	[co_trama_entrada] [varbinary](max) NULL,
	[co_trama_dto] [xml] NULL,
	[co_trama_autorizado] [varbinary](max) NULL,
	[co_hora_in] [datetime] NULL,
	[co_estatus] [smallint] NULL,
	[co_id_emisor] [int] NULL,
	[co_num_comprobante] [varchar](50) NULL,
	[co_nombre_archivo] [varchar](200) NULL,
	[co_tipo_comprobante] [smallint] NULL,
	[co_hora_reproceso] [datetime] NULL,
	[co_numero_reprocesos] [int] NULL,
	[co_id_licencia] [decimal](18, 0) NULL,
	[co_id_cliente] [decimal](18, 0) NULL,
	[co_num_autorizacion] [varchar](100) NULL,
	[co_fecha_autorizacion] [datetime] NULL,
	[co_num_comprobante_asociado] [varchar](50) NULL,
	[co_total_comprobante] [decimal](15, 2) NULL,
	[co_fecha_in] [date] NULL,
	[co_canal] [smallint] NULL,
	[co_hora_export_import] [datetime] NULL,
	[co_id_punto] [int] NULL,
	[co_pais] [smallint] NULL,
	[co_fecha_emision] [datetime] NOT NULL,
	[co_anio_emi] [int] NULL,
	[co_mes_emi] [tinyint] NOT NULL,
	[co_dia_emi] [int] NULL,
	[co_establecimiento] [varchar](10) NULL,
	[co_punto_emision] [varchar](10) NULL,
	[co_secuencia] [varchar](50) NULL,
	[co_respuesta] [smallint] NULL,
	[co_detalle] [varchar](max) NULL,
	[co_control] [varchar](50) NULL,
	[co_id] [bigint] IDENTITY(1,1) NOT NULL,
	[co_estado_notificacion] [smallint] NULL,
	[co_usuario_proceso] [int] NULL,
	[co_version] [varchar](30) NULL,
	[co_host_proceso] [varchar](30) NULL,
	[co_condicion_venta] [varchar](50) NULL,
	[co_codigo_tipo_documento] [varchar](5) NULL,
	[co_concepto] [varchar](200) NULL,
	[co_mail_notificacion] [varchar](200) NULL,
	[co_id_externo] [varchar](20) NULL,
	[co_clave_acceso] [varchar](300) NULL,
	[co_desconectado] [bit] NULL,
	[co_hora_bdd] [datetime] NULL,
	[co_guest_remoto] [varchar](50) NULL,
	[co_guest_app] [varchar](50) NULL,
	[co_guest_version] [varchar](50) NULL,
	[co_seg_proceso] [decimal](18, 0) NULL,
	[co_identificacion] [varchar](20) NULL,
	[co_tipo_identificacion] [varchar](10) NULL,
	[co_razon_social] [varchar](200) NULL,
	[co_propina] [money] NULL,
	[co_evento_aceptacion] [int] NULL,
	[co_nemonico] [varchar](10) NULL,
	[co_ruc_emisor] [varchar](100) NULL,
 CONSTRAINT [PK_com_log_comprobante_xml_id_comprobante] PRIMARY KEY NONCLUSTERED 
(
	[co_id_comprobante] ASC,
	[co_fecha_emision] ASC,
	[co_mes_emi] ASC
)
) ON [PS_MesEmision]([co_mes_emi]);
GO
